### PR TITLE
section titles css

### PR DESCRIPTION
**Pull request by simonachess**

### CODE REVIEW

**Review by Mokslams — DISMISSED** [review]

**Review by Koshakas — COMMENTED** [review]
pabandyk ištrinti settings.json iš commito

**Review by Koshakas — APPROVED** [review]
ok

**Review by Mokslams — APPROVED** [review]
+

**Review by Mokslams — APPROVED** [review]

**Review by VaidasMakstutis — APPROVED** [review]

**Review by Mokslams — APPROVED** [review]
No conflict

**Pull request merged**
